### ISSUE TITLE
webhook_logs() should support fetching pages beyond the first

### ISSUE THREAD

**Issue by szunami** [SynapseFI/SynapseRuby#4]
The docs [here](https://docs.synapsefi.com/docs/view-webhook-logs) describe the API for fetching webhook logs. The no-argument call described here will only fetch the latest page. For many use cases, this is inadequate. In experimenting, I've discovered that the HTTP API supports a query param `?page={page_number}` which can fetch other pages.

Proposals:

1. add a default argument to the method; i.e. `def webhook_logs(page_number = 1)`; this would be backwards compatible.
2. add a parameters object with a default argument, which includes a field representing `page_number`. This can also be backwards-compatible.

Happy to contribute here; let me know what you think makes sense.

**Comment by emawutor** [comment]
https://github.com/SynapseFI/SynapseRuby/blob/bdb855d043423b9e3aea83178a0b7cc28f530827/lib/synapse_api/client.rb#L240

done
