### ISSUE TITLE
User#get_node_statements redeclared

### ISSUE THREAD

**Issue by jessecurry** [SynapseFI/SynapseRuby#7]
https://github.com/SynapseFI/SynapseRuby/blob/973a602c7ee328e42d9b036a9e74e83610c09f05/lib/synapse_api/user.rb#L732

`User#get_node_statements` is redeclared, breaking existing functionality.

I have a [PR](https://github.com/SynapseFI/SynapseRuby/pull/6) that addresses this issue by renaming the new method to `generate_node_statements`

**Comment by emawutor** [comment]
done
